#!/bin/bash

#SBATCH --job-name=actor_job_2n
#SBATCH --nodes=2
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ruben.kip@student.rug.nl
#SBATCH --ntasks-per-node=1
#SBATCH --partition=short

hostname = %HOSTNAME%

srun test-run