#!/bin/bash

#SBATCH --job-name=actor_job
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=1

hostname = %HOSTNAME%

sbtach java -jar -Dakka.cluster.seed-nodes.0="akka.tcp://COPSolver@${hostname}:2552" -Dnodes=4 -Dhostname=hostname