#!/bin/bash

#SBATCH --job-name=actor_job_4n
#SBATCH --nodes=4
#SBATCH --cpus-per-task=2

#SBATCH --ntasks-per-node=1
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ruben.kip@student.rug.nl
#SBATCH --partition=short

srun java -jar -Dakka.cluster.seed-nodes.0="akka://COPSolver@$(hostname -i):2552" -Dnodes=4 -Dhostname=$(hostname -i) -Ddeployment="branch" cop-solver-assembly-1.0.jar